### ISSUE TITLE
Include Tensorflow Lite

### ISSUE THREAD

**Issue by Medinaaz** [fritzlabs/fritz-examples#44]
How did you include tensorflow models, because in your article you mention you have to install tensorflow lite but in github page you just include it in gradle as 
`aaptOptions {
        noCompress "tflite"
    }`

**Comment by hsiaoer** [comment]
Which article and github example app are you referring to?

Take a look at our documentation for working with custom TFL models: https://docs.fritz.ai/develop/custom-models/tensorflow-lite.html

You’ll need to specify ``aaptOptions`` in order to prevent compressing TensorFlow Lite models. If they're compressed on build, the model will not ru properly.

**Comment by Medinaaz** [comment]
I was using this documentation https://docs.fritz.ai/develop/vision/image-segmentation/android.html
I couldn't notice how the tensorflow lite was used inside your fritz android examples, because only the inclusion of the tensorflow lite version in gradle file was mentioned and how the segmentation was done. Thank You very much

**Comment by hsiaoer** [comment]
We use tensorflow lite models under the hood so the Android SDK already includes the TFL library. You shouldn't need to install TFL in your app if you're using our SDK. You'll just need to add the aaptOptions mentioned in those directions.

**Comment by Medinaaz** [comment]
Okay, thank you very much for the help!
